[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

eth-rpc-url="https://eth-sepolia.g.alchemy.com/v2/Z6gjDd5Sxs2ISLvmFCtQIU7CQ3c0vmdC"

# Compiler Settings
solc = '0.8.28'           		# Solidity compiler version 
optimizer = true           		# Enable optimizer 
optimizer_runs = 200
evm_version = "london"  
